image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  #- npm run export
  #- mv site.pdf public sokogskriv.pdf
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master
